# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tela\tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 519)
        MainWindow.setStyleSheet(
            "QMainWindow>QWidget{\n"
            "    background-color:#fafafa;\n"
            "}\n"
            "\n"
            "QLineEdit{\n"
            "    border: 1px solid #ccc;\n"
            "    border-radius: 5px;\n"
            "    height:20px;\n"
            "}\n"
            "\n"
            "QDateTimeEdit{\n"
            "    border: 1px solid #ccc;\n"
            "    border-radius: 5px;\n"
            "    height:20px;\n"
            "}"
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_pasta_entrada = QtWidgets.QLineEdit(self.groupBox)
        self.input_pasta_entrada.setMinimumSize(QtCore.QSize(0, 0))
        self.input_pasta_entrada.setObjectName("input_pasta_entrada")
        self.horizontalLayout.addWidget(self.input_pasta_entrada)
        self.btn_pasta_entrada = QtWidgets.QPushButton(self.groupBox)
        self.btn_pasta_entrada.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(".\\tela\\icons/2867902_plus_icon_folder.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.btn_pasta_entrada.setIcon(icon)
        self.btn_pasta_entrada.setIconSize(QtCore.QSize(24, 24))
        self.btn_pasta_entrada.setFlat(True)
        self.btn_pasta_entrada.setObjectName("btn_pasta_entrada")
        self.horizontalLayout.addWidget(self.btn_pasta_entrada)
        spacerItem = QtWidgets.QSpacerItem(
            10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.btn_add_entrada = QtWidgets.QPushButton(self.groupBox)
        self.btn_add_entrada.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(".\\tela\\icons/2867932_plus_icon_circle.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.btn_add_entrada.setIcon(icon1)
        self.btn_add_entrada.setIconSize(QtCore.QSize(24, 24))
        self.btn_add_entrada.setFlat(True)
        self.btn_add_entrada.setObjectName("btn_add_entrada")
        self.horizontalLayout.addWidget(self.btn_add_entrada)
        self.btn_remove_entrada = QtWidgets.QPushButton(self.groupBox)
        self.btn_remove_entrada.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(".\\tela\\icons/2867924_minus_icon_circle.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.btn_remove_entrada.setIcon(icon2)
        self.btn_remove_entrada.setIconSize(QtCore.QSize(24, 24))
        self.btn_remove_entrada.setFlat(True)
        self.btn_remove_entrada.setObjectName("btn_remove_entrada")
        self.horizontalLayout.addWidget(self.btn_remove_entrada)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_entrada = QtWidgets.QTableWidget(self.groupBox)
        self.table_entrada.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents
        )
        self.table_entrada.setAlternatingRowColors(True)
        self.table_entrada.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_entrada.setObjectName("table_entrada")
        self.table_entrada.setColumnCount(1)
        self.table_entrada.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_entrada.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.table_entrada)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.input_extensao = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_extensao.setMinimumSize(QtCore.QSize(0, 0))
        self.input_extensao.setMaximumSize(QtCore.QSize(40, 16777215))
        self.input_extensao.setText("")
        self.input_extensao.setObjectName("input_extensao")
        self.horizontalLayout_2.addWidget(self.input_extensao)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.input_pasta_saida = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_pasta_saida.setMinimumSize(QtCore.QSize(0, 0))
        self.input_pasta_saida.setText("")
        self.input_pasta_saida.setObjectName("input_pasta_saida")
        self.horizontalLayout_2.addWidget(self.input_pasta_saida)
        self.btn_pasta_saida = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_pasta_saida.setText("")
        self.btn_pasta_saida.setIcon(icon)
        self.btn_pasta_saida.setIconSize(QtCore.QSize(24, 24))
        self.btn_pasta_saida.setFlat(True)
        self.btn_pasta_saida.setObjectName("btn_pasta_saida")
        self.horizontalLayout_2.addWidget(self.btn_pasta_saida)
        spacerItem1 = QtWidgets.QSpacerItem(
            10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_add_saida = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_add_saida.setText("")
        self.btn_add_saida.setIcon(icon1)
        self.btn_add_saida.setIconSize(QtCore.QSize(24, 24))
        self.btn_add_saida.setFlat(True)
        self.btn_add_saida.setObjectName("btn_add_saida")
        self.horizontalLayout_2.addWidget(self.btn_add_saida)
        self.btn_remove_saida = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_remove_saida.setText("")
        self.btn_remove_saida.setIcon(icon2)
        self.btn_remove_saida.setIconSize(QtCore.QSize(24, 24))
        self.btn_remove_saida.setFlat(True)
        self.btn_remove_saida.setObjectName("btn_remove_saida")
        self.horizontalLayout_2.addWidget(self.btn_remove_saida)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.table_saida = QtWidgets.QTableWidget(self.groupBox_2)
        self.table_saida.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents
        )
        self.table_saida.setAlternatingRowColors(True)
        self.table_saida.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.table_saida.setObjectName("table_saida")
        self.table_saida.setColumnCount(2)
        self.table_saida.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_saida.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_saida.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.table_saida)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radio_diario = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_diario.setObjectName("radio_diario")
        self.verticalLayout_3.addWidget(self.radio_diario)
        self.radio_semanal = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_semanal.setObjectName("radio_semanal")
        self.verticalLayout_3.addWidget(self.radio_semanal)
        self.radio_mensal = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_mensal.setObjectName("radio_mensal")
        self.verticalLayout_3.addWidget(self.radio_mensal)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.date_inicio = QtWidgets.QDateTimeEdit(self.groupBox_3)
        self.date_inicio.setCalendarPopup(True)
        self.date_inicio.setObjectName("date_inicio")
        self.gridLayout.addWidget(self.date_inicio, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btn_agendar = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_agendar.setObjectName("btn_agendar")
        self.horizontalLayout_3.addWidget(self.btn_agendar)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 3)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", ".: Organizador de Arquivos :.")
        )
        self.groupBox.setTitle(_translate("MainWindow", "Pastas monitoradas"))
        self.label.setText(_translate("MainWindow", "Endereço:"))
        self.btn_pasta_entrada.setWhatsThis(
            _translate("MainWindow", "<html><head/><body><p>Procurar</p></body></html>")
        )
        self.btn_add_entrada.setWhatsThis(
            _translate(
                "MainWindow", "<html><head/><body><p>Adicionar</p></body></html>"
            )
        )
        self.btn_remove_entrada.setWhatsThis(
            _translate("MainWindow", "<html><head/><body><p>Remover</p></body></html>")
        )
        item = self.table_entrada.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ENDEREÇO"))
        self.label_5.setText(
            _translate(
                "MainWindow",
                "<html><head/><body><p>Todas as pastas monitoradas acima terão seus arquivos configurados para os endereços abaixo. </p></body></html>",
            )
        )
        self.groupBox_2.setTitle(_translate("MainWindow", "Pastas de saída"))
        self.label_2.setText(_translate("MainWindow", "Extensão:"))
        self.label_3.setText(_translate("MainWindow", "Pasta destino:"))
        self.btn_pasta_saida.setWhatsThis(
            _translate("MainWindow", "<html><head/><body><p>Procurar</p></body></html>")
        )
        self.btn_add_saida.setWhatsThis(
            _translate(
                "MainWindow", "<html><head/><body><p>Adicionar</p></body></html>"
            )
        )
        self.btn_remove_saida.setWhatsThis(
            _translate("MainWindow", "<html><head/><body><p>Remover</p></body></html>")
        )
        item = self.table_saida.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ENDEREÇO DESTINO"))
        item = self.table_saida.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "EXTENSÃO"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Agendamento"))
        self.radio_diario.setText(_translate("MainWindow", "Diariamente"))
        self.radio_semanal.setText(_translate("MainWindow", "Semanalmente"))
        self.radio_mensal.setText(_translate("MainWindow", "Mensalmente"))
        self.label_4.setText(_translate("MainWindow", "Iniciar em:"))
        self.btn_agendar.setText(_translate("MainWindow", "Agendar"))
